import { Toaster } from "react-hot-toast";

import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "background.default" }}>
        <Toaster position="top-center" />
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
